name       : python-lockfile
version    : 0.12.2
release    : 1
source     :
    - https://pypi.python.org/packages/source/l/lockfile/lockfile-0.12.2.tar.gz : 6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799
license    : MIT
summary    : Platform-independent file locking module
description: |
    Platform-independent file locking module
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
