name       : python-lockfile
version    : 0.12.2
release    : 2
source     :
    - https://pypi.python.org/packages/source/l/lockfile/lockfile-0.12.2.tar.gz : 6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799
license    : MIT
component  : programming.python
summary    : Platform-independent file locking module
description: |
    Platform-independent file locking module
builddeps  :
    - pbr
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
